# -*- coding: utf-8 -*-
"""simple_Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c3rQolaRZrIBjFYhOMqS4K-w6KGL15_C
"""

# Simple Rule-Based Chatbot
def chatbot():
  print("Hello! I'm Bot, your friendly chatbot. Type 'exit' or 'quit' to end the conversation.")
  print("I can answer questions about greetings, weather, time, or basic facts. What's on your mind?")
  while True:
    user_input = input("You: ").lower().strip()
    if user_input == 'exit' or user_input == 'quit':
      print("Bot: Goodbye! Have a great day!")
      break
    elif any(greeting in user_input for greeting in ['hi', 'hello', 'hey']):
      print("Bot: Hi there! How can I assist you today?")
    elif any(farewell in user_input for farewell in ['bye', 'goodbye', 'see you']):
      print("Bot: Bye! Come back anytime!")
    elif 'how are you' in user_input or 'how you doing' in user_input:
      print("Bot: I'm doing great, thanks for asking! How about you?")
    elif 'weather' in user_input:
      print("Bot: I don't have real-time weather data, but I can suggest checking a weather app! Is it sunny or rainy where you are?")
    elif 'time' in user_input:
      print("Bot: I don't have a clock, but you can check the time on your device! What's the time where you are?")
    elif 'your name' in user_input or 'who are you' in user_input:
      print("Bot: I'm GrokBot, created to chat with you! What's your name?")
    elif 'help' in user_input or 'what can you do' in user_input:
      print("Bot: I can respond to greetings, farewells, questions about the weather, time, or basic facts. Try asking me something like 'How are you?' or 'What's the weather?'")
    elif 'capital of india' in user_input:
      print("Bot: The capital of India is New Delhi!")
    elif 'largest planet' in user_input:
      print("Bot: The largest planet in our solar system is Jupiter!")
    elif 'joke' in user_input or 'tell me a joke' in user_input:
      print("Bot: Why did the computer go to art school? Because it wanted to learn how to draw a better 'byte'!")
    elif any(feeling in user_input for feeling in ['happy', 'sad', 'angry']):
      if 'happy' in user_input:
        print("Bot: That's awesome to hear! What's making you happy today?")
      elif 'sad' in user_input:
        print("Bot: I'm sorry you're feeling sad. Want to share what's going on?")
      elif 'angry' in user_input:
        print("Bot: Oh no, what's got you angry? I'm here to listen!")
      else:
        print("Bot: Hmm, I'm not sure how to respond to that. Try asking about the weather, time, or a fun fact!")

chatbot()